Distpg 250 disable llvm centos8 12
percona/postgresql-docs pull request #102
Opened 2021-06-08 13:49 UTC by nastena1606

2021-06-08 18:06 UTC, EvgeniyPatlan requested changes

2021-06-08 18:06 UTC, EvgeniyPatlan commented on docs/installing.md
> +>On Debian 9 (stretch), you need to [enable the llvm repository](https://apt.llvm.org/)
I am not sure we need this as we already added llvm into our repos

2021-06-09 05:56 UTC, mu-samoylov approved these changes

2021-06-10 11:20 UTC, EvgeniyPatlan approved these changes

2021-06-10 15:16 UTC, merged