Distpg-71 release notes 12.2
percona/postgresql-docs pull request #15
Opened 2020-05-11 06:52 UTC by nastena1606

2020-05-11 08:12 UTC, borys-belinsky approved these changes

2020-05-11 08:19 UTC, EvgeniyPatlan commented on source/installing.rst
> +   $ sudo percona-release setup ppg12
just a question.
We are going to issue ppg-12.2 but why we do not show how to install this distribution but generic only?

2020-05-11 08:31 UTC, EvgeniyPatlan commented on source/installing.rst
> +   $ sudo percona-release setup ppg12
This comes from that we have special repo for each distribution and that is why this format doesn't suit for distributions

2020-05-11 08:32 UTC, EvgeniyPatlan requested changes
we need to show that ppg-12.2 should be used.
ppg-12 is generic repo and it just accumulates all pgg-12 packages
the same about ppg-11

2020-05-12 19:13 UTC, EvgeniyPatlan requested changes

2020-05-12 19:13 UTC, EvgeniyPatlan commented on source/installing.rst
> +   $ sudo percona-release setup ppg12.2
there are 2 ways to call setup with and without dash
percona-release setup ppg12.2 or percona-release setup ppg-12.2
as for me it is better to use variant with dash

2020-05-14 08:33 UTC, EvgeniyPatlan approved these changes

2020-05-15 15:49 UTC, merged