DISTPG-368-Release-notes-12.9
percona/postgresql-docs pull request #181
Opened 2021-12-10 07:58 UTC by nastena1606

modified:   .github/workflows/main.yml
	new file:   docs/release-notes-v12.9.md
	modified:   docs/release-notes.md
	modified:   mkdocs-base.yml

2021-12-10 13:27 UTC, EvgeniyPatlan requested changes

2021-12-10 13:27 UTC, EvgeniyPatlan commented on docs/release-notes-v12.9.md
> +| [pg_stat_monitor](https://github.com/percona/pg_stat_monitor)                                            | 1.0.0 - Beta 2   | collects and aggregates statistics for PostgreSQL and provides histogra
we have RC1

2021-12-10 13:35 UTC, nastena1606 commented on docs/release-notes-v12.9.md
> +| [pg_stat_monitor](https://github.com/percona/pg_stat_monitor)                                            | 1.0.0 - Beta 2   | collects and aggregates statistics for PostgreSQL and provides histogra
Fixed

2021-12-10 13:49 UTC, EvgeniyPatlan requested changes

2021-12-10 13:49 UTC, EvgeniyPatlan commented on docs/release-notes-v12.9.md
> +| [pg_stat_monitor](https://github.com/percona/pg_stat_monitor)                                            | 1.0.0 - RC   | collects and aggregates statistics for PostgreSQL and provides histogram in
it is rc.1 not just rc

2021-12-10 13:58 UTC, EvgeniyPatlan approved these changes

2021-12-10 15:17 UTC, LenzGr approved these changes
Looks good to me - thank you @EvgeniyPatlan for confirming the version numbers!

2021-12-13 09:46 UTC, EngineeredVirus approved these changes
LGTM

2021-12-13 13:55 UTC, merged