DISTPG-386 Release notes 13.6
percona/postgresql-docs pull request #195
Opened 2022-03-18 16:41 UTC by nastena1606

modified:   .github/workflows/main.yml
	new file:   docs/release-notes-v13.6.md
	modified:   docs/release-notes.md
	modified:   mkdocs-base.ym

2022-03-21 12:00 UTC, LenzGr commented on docs/release-notes-v13.6.md
> +- `llvm` 12.0.1 packages for Red Hat Enterprise Linux 8 / CentOS 8. These fix compatibility issues with LLVM from upstream.
```suggestion
- `llvm` 12.0.1 packages for Red Hat Enterprise Linux 8 (and compatible derivatives). These fix compatibility issues with LLVM from upstream. 
```

2022-03-21 12:01 UTC, LenzGr commented on docs/release-notes-v13.6.md
> +| CentOS 8            | `etcd`               | 3.3.11  | A consistent, distributed key-value store|
```suggestion
| RHEL 7            |`python3-python-etcd` | 0.4.3   | A Python client for ETCD     |
| RHEL 8            | `etcd`               | 3.3.11  | A consistent, distributed key-value store|
```

2022-03-21 12:13 UTC, nastena1606 commented on docs/release-notes-v13.6.md
> +- `llvm` 12.0.1 packages for Red Hat Enterprise Linux 8 / CentOS 8. These fix compatibility issues with LLVM from upstream.
Fixed

2022-03-21 12:13 UTC, nastena1606 commented on docs/release-notes-v13.6.md
> +| CentOS 8            | `etcd`               | 3.3.11  | A consistent, distributed key-value store|
Fixed

2022-03-22 08:10 UTC, EvgeniyPatlan requested changes

2022-03-22 08:10 UTC, EvgeniyPatlan commented on mkdocs-base.yml
> +          cover_subtitle: 13.6 (March 21, 2022)
date is in the past

2022-03-22 17:07 UTC, merged