DISTPG-483 Release notes 15.0
percona/postgresql-docs pull request #262
Opened 2022-09-23 14:46 UTC by nastena1606

2022-10-18 09:14 UTC, capri1989 requested changes

2022-10-18 09:14 UTC, ImTheKai commented on docs/release-notes-v15.0.md
> +| [Patroni](https://patroni.readthedocs.io/en/latest/) | 2.1.1 | a HA (High Availability) solution for PostgreSQL |
We do ship Patroni version 2.1.4

2022-10-18 09:14 UTC, ImTheKai commented on docs/release-notes-v15.0.md
> +|[`wal2json`](https://github.com/eulerto/wal2json) |2.4        | a PostgreSQL logical decoding JSON output plugin.|
wal2json is version 2.5

2022-10-18 09:14 UTC, ImTheKai commented on docs/release-notes-v15.0.md
> +|[HAProxy](http://www.haproxy.org/) | 2.5.8 | The high-availability and load balancing solution for PostgreSQL|
HAProxy is version 2.5.9

2022-10-18 09:14 UTC, capri1989 commented on docs/release-notes-v15.0.md
> +| [pg_stat_monitor](https://github.com/percona/pg_stat_monitor)| 1.1.1 - Beta2 | collects and aggregates statistics for PostgreSQL and provides histogram information.       |
PGSM version is 1.1.1 - no Beta

2022-10-18 09:14 UTC, ImTheKai commented on docs/release-notes-v15.0.md
> +| [pgBackRest](https://pgbackrest.org/)           | 2.40    | a backup and restore solution for PostgreSQL       |
pgBackRest is version 2.41

2022-10-19 09:11 UTC, capri1989 commented on docs/release-notes-v15.0.md
> +| [PostgreSQL Common](https://packages.debian.org/sid/percona-postgresql-common)| 243 | PostgreSQL database-cluster manager. It provides a structure under which multiple versions of PostgreSQL may be
postgresql-common version is 241

2022-10-21 17:40 UTC, umairshahid requested changes
When we talk about benefits of the distribution, perhaps we should focus on the user problems we are trying to solve. One way is to talk about High Availability and how we recommend addressing it using our reference architecture available here: https://www.percona.com/ha-for-postgresql

2022-10-22 13:06 UTC, nastena1606 commented
@umairshahid  Could you please elaborate? I'm not sure I understand the request. Do you want me to rewrite the release notes from the benefit point of view?

2022-10-24 07:44 UTC, nastena1606 commented on docs/release-notes-v15.0.md
> +| [PostgreSQL Common](https://packages.debian.org/sid/percona-postgresql-common)| 243 | PostgreSQL database-cluster manager. It provides a structure under which multiple versions of PostgreSQL may be
Fixed

2022-10-24 07:44 UTC, nastena1606 commented on docs/release-notes-v15.0.md
> +| [pgBackRest](https://pgbackrest.org/)           | 2.40    | a backup and restore solution for PostgreSQL       |
Fixed

2022-10-24 07:44 UTC, nastena1606 commented on docs/release-notes-v15.0.md
> +| [pg_stat_monitor](https://github.com/percona/pg_stat_monitor)| 1.1.1 - Beta2 | collects and aggregates statistics for PostgreSQL and provides histogram information.       |
Fixed

2022-10-24 07:45 UTC, nastena1606 commented on docs/release-notes-v15.0.md
> +|[HAProxy](http://www.haproxy.org/) | 2.5.8 | The high-availability and load balancing solution for PostgreSQL|
Fixed

2022-10-24 07:53 UTC, nastena1606 commented on docs/release-notes-v15.0.md
> +| [Patroni](https://patroni.readthedocs.io/en/latest/) | 2.1.1 | a HA (High Availability) solution for PostgreSQL |
fixed

2022-10-24 07:53 UTC, nastena1606 commented on docs/release-notes-v15.0.md
> +|[`wal2json`](https://github.com/eulerto/wal2json) |2.4        | a PostgreSQL logical decoding JSON output plugin.|
fixed

2022-10-24 09:05 UTC, capri1989 approved these changes
LGTM

2022-10-24 13:23 UTC, umairshahid commented
@nastena1606 when we describe our distribution, we say " ... aim to simplify deployment and management of your PostgreSQL environment ... ". My suggestion is to talk about user problems that we envision addressing in our PostgreSQL strategy. For example, I might say something like: 

"We are pleased to announce the launch of Percona Distribution for PostgreSQL 15.0 - a clustering solution to assist you in deploying and managing PostgreSQL. The distribution aims to address common operational issues facing enterprises when using PostgreSQL like High Availability, Disaster Recovery, Security, Performance, & Scalability."

Then, in the 'See Also' section, we can add another link to the HA page on our website.

2022-10-24 13:44 UTC, nastena1606 commented
Thank you for the clarification and ideas.

2022-10-24 20:56 UTC, merged