DISTPG-539 Release notes 15.2
percona/postgresql-docs pull request #320
Opened 2023-01-30 11:11 UTC by nastena1606

modified:   .github/workflows/main.yml
	modified:   docs/index.md
	modified:   docs/release-notes.md
	modified:   mkdocs-base.yml
new doc: docs/release-notes-v15.2.md

2023-03-16 18:39 UTC, capri1989 requested changes

2023-03-16 18:39 UTC, capri1989 commented on docs/index.md
> +* [PostGIS](https://trac.osgeo.org/postgis/) - a spatial database extender for PostgreSQL. It allows GIS (Geographic Information Systems) objects to be stored in the database.
We don't ship PostGIS with this update

2023-03-16 18:39 UTC, capri1989 commented on docs/release-notes-v15.2.md
> +| [PostGIS](https://trac.osgeo.org/postgis/) |  | a spatial database extender for PostgreSQL.|
We don't ship PostGIS in this release

2023-03-16 20:01 UTC, nastena1606 commented on docs/release-notes-v15.2.md
> +| [PostGIS](https://trac.osgeo.org/postgis/) |  | a spatial database extender for PostgreSQL.|
Updated. Thanks for spotting it!

2023-03-16 20:01 UTC, nastena1606 commented on docs/index.md
> +* [PostGIS](https://trac.osgeo.org/postgis/) - a spatial database extender for PostgreSQL. It allows GIS (Geographic Information Systems) objects to be stored in the database.
Updated

2023-03-17 10:44 UTC, capri1989 approved these changes

2023-03-17 16:46 UTC, Naeem-Akhter approved these changes
LGTM!

2023-03-20 19:43 UTC, merged