DISTPG-570 PostGIS documentation
percona/postgresql-docs pull request #370
Opened 2023-05-12 14:55 UTC by nastena1606

new file:   docs/postgis.md
	modified:   mkdocs-base.yml

2023-06-09 06:55 UTC, capri1989 approved these changes
Tested the install and setup of PPG 15.3 and PostGIS on Ubuntu 22.04. Also run some basic testing taken from https://postgis.net/docs/postgis_installation.html#install_requirements and it all passed. 

LGTM

2023-06-09 07:27 UTC, EvgeniyPatlan approved these changes

2023-06-09 16:31 UTC, EvgeniyPatlan requested changes

2023-06-09 16:31 UTC, EvgeniyPatlan commented on docs/solutions/postgis-deploy.md
> +
Also it is needed to install epel repository
 sudo yum install epel-release
 Also on ol9 and ol8 it is needed to enable `code ready builder` repository
 sudo dnf config-manager --set-enabled ol8_codeready_builder - ol8
 sudo dnf config-manager --set-enabled ol9_codeready_builder - ol9

2023-06-28 10:20 UTC, EvgeniyPatlan approved these changes

2023-06-28 15:19 UTC, Naeem-Akhter approved these changes
LGTM!

2023-06-28 19:18 UTC, merged