DISTPG-897 Documented install from tarball steps for PG server
percona/postgresql-docs pull request #591
Opened 2024-06-06 12:20 UTC by nastena1606

PG-789 Added a step to set path for createuser binary

modified:   docs/enable-extensions.md
        new file:   docs/tarball.md
        modified:   docs/uninstalling.md

2024-06-07 07:24 UTC, shahidullah79 commented
@nastena1606  IMO the text should be like 
To use the createuser binary to create a database user, set the LD_LIBRARY_PATH environment variable to the server's library path.

2024-06-21 20:06 UTC, Naeem-Akhter approved these changes

2024-06-24 06:13 UTC, maqeel75 commented on docs/tarball.md
> +| percona-postgresql{{pgversion}}| A metapackage that installs the latest version of PostgreSQL. It also includes the following extensions: <br> - `pgaudit` <br> - `pgAudit_set_user` <br> - `pg_repac
percona-postgresql{{pgversion}} is not a meta package in case of tarball. It is in fact complete PostgreSQL server with its extensions.

2024-06-24 06:18 UTC, maqeel75 commented on docs/tarball.md
> +5. If you extracted the tarball somewhere else in your system, copy `percona-python3`, `percona-tcl` and `percona-perl` to the `/opt` directory. This is required for the correct run of libraries that
I would suggest write it as follows:

If you have extracted the tarball in a directory other than /opt, copy `percona-python3`, `percona-tcl` and `percona-perl` to the `/opt` directory. This is required for the correct run of libraries that require those modules.

2024-06-24 06:23 UTC, maqeel75 requested changes
Check my comments

2024-06-24 08:12 UTC, maqeel75 approved these changes
LGTM

2024-06-24 08:42 UTC, shahidullah79 commented
LGTM

2024-06-24 09:08 UTC, shahidullah79 reviewed
LGTM

2024-06-24 09:44 UTC, merged